
version: '3.6'

services:
  gochan:
    image: gochan:latest
    container_name: gochan
    ports:
      - 4433:4433
    volumes:
      - imagedir:/usr/src/app/static/images
    restart_policy:
      condition: any
      delay: 2s
      max_attempts: 5
      window: 10s

volumes:
  imagedir:
